name: Build

on:
- push

jobs:
  show_ssh_private_key_file_name:
    name: "Show SSH private key file name"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - id: show_private_key_file_name
          uses: ./.
          with:
              key: "fake key"
        - run: echo key file name ${{ steps.show_private_key_file_name.outputs.key_file_name }}
          shell: bash
